# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.IntegerField(default=0)),
                ('goal_amount', models.IntegerField()),
                ('end_date', models.DateTimeField(verbose_name='Due')),
            ],
        ),
    ]
