# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
