# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_goal', '0002_goal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(verbose_name='Due'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_goal.Goal'),
        ),
    ]
